---
title: "고통분 과제1"
author: "백지우"
date: "2026-10-06"
output: pdf_document
---

Problem 1
```{r}
library(ggplot2)

set.seed(1)
n = 200
x = seq(0, 1, length.out = n)
y = sin(2*pi*x) + rnorm(n, sd = 0.15)

df <- data.frame(x = x, y = y)
write.csv(df, "Data/hw1_data.csv", row.names = FALSE)

# problem 1 - (b),(c) 문제의 r 스크립트는 깃허브에 올라온 프로젝트 폴더 '/R'에 있습니다.
```

problem 2
```{r}
# 버블 정렬 구현
bubble_sort = function(vec, decreasing = FALSE){
  n = length(vec)
  if(n<=1) return(vec)
  for(i in 1:(n-1)){
    for(j in 1:(n-i)){
      condition = if(decreasing) vec[j] < vec[j+1] else vec[j] > vec[j+1]
      if(condition) {
        temp = vec[j]
        vec[j] = vec[j+1]
        vec[j+1] = temp
      }
    }
  }
  return(vec)
}

set.seed(1)
test = runif(10)

bubble_sort(test) # 오름차순
bubble_sort(test, TRUE) # 내림차순
```
```{r}
# 퀵 정렬 구현
quick_sort = function(a, decreasing=FALSE){
  if(length(a)<=1) return(a)
  pivot = a[1]
  rest = a[-1]
  
  if(decreasing) {
    left = rest[rest >= pivot]
    right = rest[rest < pivot]
  }
  else{
    left = rest[rest < pivot]
    right = rest[rest >= pivot]
  }
  return(c(quick_sort(left, decreasing), pivot, quick_sort(right, decreasing)))
}
quick_sort(test) # 오름차순
quick_sort(test, TRUE) # 내림차순
```


problem 3
```{r}
num_miboon = function(f, x, h= 1e-6, method = "central"){
  if(method =="forward") {
    return((f(x+h)-f(x))/h)
  }
  if(method == "backward"){
    return((f(x)-f(x-h))/h)
  }
  if(method == "central"){
    return((f(x+h)-f(x-h))/(2*h))
  }
}

target_f = function(x){
  cos(x) - x
}
prime_f = function(x){
  -sin(x) - 1
}

target_x = seq(0, 2*pi, length.out=100)

real_f = prime_f(target_x)

ff1 = num_miboon(target_f, target_x, method = "forward")
ff2 = num_miboon(target_f, target_x, method = "backward")
ff3 = num_miboon(target_f, target_x, method="central")

# 도함수 시각화

df = data.frame(
  x = target_x,
  real_f,
  ff1
)

ggplot(df, aes(x=x)) +
  geom_line(aes(y = real_f, color="해석적 미분"), linewidth = 1) +
  geom_line(aes(y = ff1, color="수치 미분"), linetype="dashed", linewidth =1) +
  labs(title = "해석적 미분 vs 수치 미분 시각화", x="x", y = NULL, color = "그래프 종류") +
  scale_color_manual(
    values = c("해석적 미분" = "blue",
               "수치 미분" = "red")
  ) +
  theme_minimal()


Newton_Rapshon = function(f,
                          fprime=NULL,
                          x0,
                          maxiter=100,
                          h=1e-6,
                          epsilon=1e-10){
  x_t = x0
    for(i in 1:maxiter){
      if(is.null(fprime)){
        deriv = num_miboon(f, x_t, h, method = "central")
      }
      else {
        deriv = fprime(x_t)
      }
      x_next = x_t - (f(x_t)/deriv)
      if(abs(x_next - x_t) < epsilon) {
        return(x_next)
      }
      x_t = x_next
    }
  return(x_t)
}
# 수치 미분 버전
Newton_Rapshon(target_f, fprime = NULL, x0 = 0.5)
# 도함수 제공 버전
Newton_Rapshon(target_f, fprime = prime_f, x0 = 0.5)
```


problem 4
```{r}
left_rectangle = function(f, a, b, n){
  h = (b-a) / n
  xi = a + (0:n-1)*h
  fi = f(xi)
  result = h * sum(f(xi))
  return(result)
}

trapezoid = function(f, a, b, n){
  h = (b-a) / n
  xi = a + (0:n)*h
  fi = f(xi)
  result = (h/2) * (fi[1] + 2 * sum(fi[2:n]) + fi[n+1])
  return(result)
}

simpson = function(f, a, b, n){
  if (n %% 2 != 0) {
    stop("n은 반드시 짝수여야 합니다.")
  }
  h = (b-a) / n
  xi = a + (0:n)*h
  fi = f(xi)
  result = (h/3) * (fi[1] + 4*sum(fi[seq(2, n, by=2)]) + 2*sum(fi[seq(3, n-1, by=2)])) 
  return(result)
  }

left_rectangle(func, 0, pi, 100)
trapezoid(func, 0, pi, 100)
simpson(func, 0, pi, 100)

n_val = c(10, 30, 60, 100, 150, 200)
func = function(x){
  sin(x)
}
true_val = 2

err_l = c()
err_t = c()
err_s = c()
  
for(i in n_val){
  err_l = c(err_l, abs(left_rectangle(func, 0, pi, i) - true_val)) 
  err_t = c(err_t, abs(trapezoid(func, 0, pi, i) - true_val))
  err_s = c(err_s, abs(simpson(func, 0, pi, i) - true_val))
}
df_err = data.frame(
  n = rep(n_val, 3),
  error = c(err_l, err_t, err_s),
  method = factor(
  rep(c("Left Rectangle", "Trapezoid", "Simpson"), each = length(n_val)),
levels = c("Left Rectangle", "Trapezoid", "Simpson")
  )
)
  
ggplot(df_err, aes(x = n, y = error, color = method, shape = method)) +
  geom_line(linewidth = 1) +
  geom_point(size = 3) +
  labs(
    title = "수치적분 알고리즘별 오차 비교",
    x = "n",
    y = "오차 (Log scale)"
  ) +
  scale_color_manual(
    values = c("Left Rectangle" = "black", 
               "Trapezoid" = "blue", 
               "Simpson" = "red")
  ) +
theme_minimal()
```
problem 5
```{r}
A = matrix(c(4,2,2,2,5,1,2,1,3),3)
U = chol(A)
L = t(U)
print(L %*% t(L))

forward = function(L, b){
  n=length(b)
  z = numeric(n)
  for(i in 1:n) {
    sum_lz = if(i==1) 0 else sum(L[i, 1:(i-1)] * z[1:(i-1)])
    z[i] = (1/L[i,i]) * (b[i] - sum_lz)
  }
  return(z)
}

backward = function(L,z) {
  n = length(z)
  x = numeric(n)
  for(i in n:1){
    sum_lx = if(i == n) 0 else sum(L[(i+1):n, i] * x[(i+1):n])
    x[i] = (1/L[i,i]) * (z[i] - sum_lx)
  }
  return(x)
}

b = c(1, -2, 3)
z = forward(L, b)
forwardsolve(L, b)

x=backward(L, z)
x
solve(A, b)
```

problem 6
```{r}
gaussian_kernel = function(x1, x2, rho=1){
  exp(-rho(x1 - x2)^2)
}

fit_krr = function(x, y, lam=0.0001, rho=1){
  n = length(x)
  k = outer(x, x, FUN = function(a, b) exp(-rho*(a-b)^2))
  alpha = solve(k + lam*diag(n)) %*% y
  model = list(alpha = alpha, x=x, y=y, rho=rho, lamda=lam)
  class(model) = "krr"
  return(model)
}

predict.krr = function(ob, data){
  pre = sapply(data, function(nx){
    k_vec = exp(-ob$rho*(nx-ob$x)^2)
    sum(k_vec * ob$alpha)
  })
  return(pre)
}

plot.krr = function(ob) {
  plot(ob$x, ob$y, col = "skyblue", pch = 16,
       xlab="x", ylab="y", main = "Kernel Ridge Regression")
  x_seq = seq(min(ob$x), max(ob$x), length.out=100)
  y_pre = predict(ob, x_seq)
  lines(x_seq, y_pre, col="purple", lwd=2)
  legend("bottomleft", 
         legend = c("실제 데이터", "KRR 예측 곡선"),
         col = c("skyblue", "purple"),
         pch = c(16, NA),
         lty = c(NA, 1),
         lwd = c(NA, 2))
}

# 제시된 시험 데이터 생성
set.seed(1)
n <- 150
x_sim <- matrix(runif(n, -1, 1), ncol = 1)
f_true <- function(x) sin(2*pi*x) + 0.5*cos(4*pi*x)
y_sim <- f_true(x_sim[,1]) + rnorm(n, sd = 0.1)

# 시험 데이터 시뮬레이션
model_krr = fit_krr(x_sim[,1], y_sim)
plot(model_krr)




```




